name: DR
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Hello Workflow ]
    types: [ completed ]
        
jobs:
  dr:
    name: DR
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
         echo conclusiuon: ${{ github.event.workflow_run.conclusion }}
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
          echo "[DR](../workflows/DR.yml)" >> $GITHUB_STEP_SUMMARY
      
  dr-api-prod:
    name: DR API
    runs-on: ubuntu-latest
    needs: dr
    environment:
      name: 'DR'
      url: api.sample-dotnet.local
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: 'DR Step 1'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Deploy Step 1"
  
      - name: 'DR Step 2'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Deploy Step 2"
  
      - name: 'DR Step 3'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Deploy Step 13"
          
  dr-fe-prod:
    name: DR Front End
    runs-on: ubuntu-latest
    needs: dr
    environment:
      name: 'DR'
      url: fe.sample-dotnet.local
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: 'DR Step 1'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Deploy Step 1"
  
      - name: 'DR Step 2'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Deploy Step 2"
  
      - name: 'DR Step 3'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Deploy Step 13"
          
  test-smoke-dr:
    name: Smoke Test in DR
    needs: [dr-api-prod, dr-fe-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: 'Smoke Test Step 1'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Test Step 1"
  
      - name: 'Smoke Test Step 2'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Test Step 2"
  
      - name: 'Smoke Test Step 3'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Test Step 13"
