name: Hello Workflow
on: push
jobs:
  build:
    name: Hello Workflow Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Build Step 1'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Build Step 1"
            
      - name: 'Build Step 2'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Build Step 2"
          
      - name: 'Build Step 3'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Build Step 13"