name: Hello Workflow
on: 
  push:
  workflow_dispatch:
  
jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1
          
  build-fe:
    name: Build FrontEnd
    runs-on: ubuntu-latest
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1

  deploy-api-dev:
    name: Deploy API
    runs-on: ubuntu-latest
    needs: build-api
    environment:
      name: 'Development'
      url: api.development.sample-dotnet.local
      
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1

          
  test-api-dev:
    name: Test API
    needs: deploy-api-dev
    runs-on: ubuntu-latest
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1
  
          
  deploy-fe-dev:
    name: Deploy Front End
    runs-on: ubuntu-latest
    needs: build-fe
    environment:
      name: 'Development'
      url: fe.development.sample-dotnet.local
    
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1
          
  test-fe-dev:
    name: Test Front End
    needs: deploy-fe-dev
    runs-on: ubuntu-latest
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1
          
  test-integration-dev:
    name: Integration Test
    needs: [test-api-dev, test-fe-dev]
    runs-on: ubuntu-latest
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1

  deploy-api-uat:
    name: Deploy API UAT
    runs-on: ubuntu-latest
    needs: test-integration-dev
    environment:
      name: 'UAT'
      url: api.uat.sample-dotnet.local
    
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1
  
  deploy-fe-uat:
    name: Deploy Front End UAT
    runs-on: ubuntu-latest
    needs: test-integration-dev
    environment:
      name: 'UAT'
      url: fe.uat.sample-dotnet.local
      
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1
  
  test-integration-uat:
    name: Integration Test in UAT
    needs: [deploy-api-uat, deploy-fe-uat]
    runs-on: ubuntu-latest
    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1
        
  deploy-api-prod:
    name: Deploy API Production
    runs-on: ubuntu-latest
    needs: test-integration-uat
    environment:
      name: 'Production'
      url: api.sample-dotnet.local

    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1

  deploy-fe-prod:
    name: Deploy Front Production
    runs-on: ubuntu-latest
    needs: test-integration-uat
    environment:
      name: 'Production'
      url: fe.sample-dotnet.local

    steps:
      - name: 'Build Step 1'
        run: |
          echo step 1
