name: 'GitOps Publish'
on:
  workflow_dispatch: 
  push:
    branches:
      - 'release/**'
    
jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
    steps:
      - name: Checkout

        uses: actions/checkout@v3

      - name: 'Build Step 1'
        uses: ./.github/actions/hello
        with:
          MOCK_STEP_NAME: "Build Step 1"
